---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-shenle
  labels:
    k8s-app: go-web
    version: v2.0
  namespace: default
spec:
  selector:
    matchLabels:
      app: go-web
  replicas: 1
  template:
    metadata:
      labels:
        app: go-web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kube-proxy
                operator: NotIn
                values:
                - "true"
      containers:
        - name: go-web
          image: ishenle/hellogo:v2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 5Mi

---
apiVersion: v1
kind: Service
metadata:
  name:  go-web-shenle
  annotations:
    ingress/http: "true"
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app: go-web
