---
apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: kubectl
    app: tools
    version: v1.0
  name: client-shenle
spec:
  imagePullSecrets:
  - name: image-pull-secret
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - image: r.addops.soft.360.cn/k8s-container/sre-tools:v1.0
    name: client
    command: ["/bin/sh", "-c"]
    args: ["/usr/bin/tail", "-f", "/etc/hosts"]
    tty: true
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 10Mi
  restartPolicy: Always
